* elscreen-around-desktop.el

** What is it ?

  elscreen-around-desktop provides the following features using desktop.el.

  + Saves elscreen tabs, history and nicknames of each frame at the end of the session
  + Restores them at the start of the session
  + Auto save synchronously with desktop-auto-save
  + Interactive functions which emulate functions defined in desktop.el.

** Requirements

   + GNU Emacs 24.4 or later
   + elscreen.el ([[https://github.com/emacs-jp/elscreen]] fixed branch)

   Tested with GNU Emaccs 24.4 (emacs-mac-app @5.4_0)

** Setup
  #+BEGIN_SRC emacs-lisp
    (add-to-list 'load-path "/path/to/elscreen")
    (add-to-list 'load-path "/path/to/elscreen-around-desktop")
    (elscreen-start)
    (require 'elscreen-around-desktop)
    (desktop-save-mode t)
    (elscreen-around-desktop-mode t)
  #+END_SRC

   If you want to turn off auto save, set =elsc-desk:auto-store-activep= to nil.
   
   #+BEGIN_SRC emacs-lisp
     (setq elsc-desk:auto-store-activep nil)
   #+END_SRC

** Custom Variable

**** elsc-desk:filename

    Default : (convert-standard-filename ".elscreen-around-desktop")
    
    ElScreen configurations is saved to the file in desktop-dirname directory.

** Interactive functions which emulate functions defined in desktop.el

  + elscreen-desktop-clear
  + elscreen-desktop-save
  + elscreen-desktop-save-in-desktop-dir
  + elscreen-desktop-read
  + elscreen-desktop-change-dir
  + elscreen-desktop-remove
  + elscreen-desktop-revert

** Background

    This was inspired by 

    [[http://stackoverflow.com/questions/22445670/save-and-restore-elscreen-tabs-and-split-frames]]

    [[https://github.com/robario/elscreen-persist]]

    I learn programming as a hobby. I will learn more about that and English.

    Thank you for your help and advice.

    趣味でプログラミングを学んでいるため，詰めが甘い箇所が多々あると思います．ご意見など頂けると幸いです．
