#+title:elscreen-around-desktop.el
#+OPTIONS: author:nil timestamp:nil  num:nil creator:nil

* What is it ?

  elscreen-around-desktop provides the following features by use of desktop.el.

  + Restore elscreen tabs, history and nicknames of each frame at the start of the session
  + Save at the end of the session
  + Auto save synchronously with desktop-auto-save
  + Interactive functions which emulate desktop-read, desktop-save, etc.

  This was tested on Emacs 24.4.1 (emacs-mac-app 5.2_0)

* Requirements

  Emacs 24.4

  elscreen.el : [[https://github.com/emacs-jp/elscreen]]

* Installation
  
  git clone https://github.com/momomo5717/elscreen-around-desktop.git

* Setup
  #+BEGIN_SRC emacs-lisp
    (add-to-list 'load-path "/path/to/elscreen")
    (add-to-list 'load-path "/path/to/elscreen-around-desktop")
    (elscreen-start)
    (require 'elscreen-around-desktop)
    (desktop-save-mode t)
    (elscreen-around-desktop-start)
  #+END_SRC
   
   You can use M-x elscreen-around-desktop-mode-off , if you want to turn off the mode.

   If you want to turn off auto save,
   
   #+BEGIN_SRC emacs-lisp
     (setq elsc-desk:auto-store-activep nil)
   #+END_SRC

* Custom Variable

*** elsc-desk:filename

    Default : (convert-standard-filename ".elscreen-around-desktop")
    
    ElScreen configurations is saved to the file in desktop-dirname directory.

* Interactive functions which emulate functions written in desktop.el

  + elscreen-desktop-save
  + elscreen-desktop-save-in-desktop-dir
  + elscreen-desktop-read
  + elscreen-desktop-change-dir
  + elscreen-desktop-remove
  + elscreen-desktop-revert

* Background

    This was inspired by 

    [[http://stackoverflow.com/questions/22445670/save-and-restore-elscreen-tabs-and-split-frames]]

    [[https://github.com/robario/elscreen-persist]]

    I learn programming as a hobby. I will learn more about that and English.

    Thank you for your help and advice.

    趣味でプログラミングを学んでいるため，詰めが甘い箇所が多々あると思います．ご意見など頂けると幸いです．
